[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mlx",
    "mlx-lm",
    "mlx-audio",
    "misaki[en]",
    "en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
    "numpy",
    "pydantic",
    "rich",
    "sounddevice",
    "webrtcvad-wheels",
]
